/****************************************************************
*   This file is generated by Dolag Houdini Tool automatically
*   You can simply include this file and use it's function
*****************************************************************/

#ifndef _DOLAG_H_
#define _DOLAG_H_

// 112
function void foo()
{
        printf("%d", 114514);
}
#endif _DOLAG_H_